theme: jekyll-theme-slate
title: This is the personal homepage of the lover boy
description: What you will find here are some of my projects and personal portofolio. Please let me know for further inquiries. 
plugins:
  - jemoji
url: "https://ANakagungdcip3.github.io/;
markdown: kramdown